[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:wasp-server]
command=sh -c "cd /app/.wasp/out/db && npx prisma db push --schema=./schema.prisma --accept-data-loss && cd /app/.wasp/out/server && node --enable-source-maps -r dotenv/config bundle/server.js"
directory=/app/.wasp/out/server
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=NODE_ENV="production"
